<?php
namespace App\Livewire\LMS\Teachers;
use App\Models\School; use App\Models\Teacher; use Illuminate\Foundation\Auth\Access\AuthorizesRequests; use Illuminate\Validation\Rule; use Illuminate\Validation\ValidationException; use Jantinnerezo\LivewireAlert\Facades\LivewireAlert; use Livewire\Attributes\Layout; use Livewire\Component; use Livewire\WithPagination; use Throwable;

#[Layout('layouts.lms')]
class Index extends Component
{
    use AuthorizesRequests;
    use WithPagination;
    public bool $showFormModal=false,$showDeleteModal=false; public ?int $editingId=null,$deletingId=null;
    public string $employeeId='',$firstName='',$middleName='',$lastName='',$phone='',$email='',$employmentDate='',$status='active';
    public function mount():void{$this->authorize('viewAny',Teacher::class);}
    public function create():void{$this->authorize('create',Teacher::class);$this->resetForm();$this->showFormModal=true;}
    public function edit(Teacher $teacher):void{$this->authorize('update',$teacher);$this->editingId=$teacher->id;$this->employeeId=$teacher->employee_id;$this->firstName=$teacher->first_name;$this->middleName=$teacher->middle_name??'';$this->lastName=$teacher->last_name;$this->phone=$teacher->phone??'';$this->email=$teacher->email??'';$this->employmentDate=$teacher->employment_date?->toDateString()??'';$this->status=$teacher->status;$this->showFormModal=true;}
    public function save():void{$teacher=$this->editingId?Teacher::findOrFail($this->editingId):null;$this->authorize($teacher?'update':'create',$teacher??Teacher::class);$schoolId=$teacher?->school_id??School::query()->value('id');abort_unless($schoolId,422,'Configure a school before adding a teacher.');try{$data=$this->validate(['employeeId'=>['required','string','max:50',Rule::unique('teachers','employee_id')->ignore($teacher?->id)],'firstName'=>['required','string','max:100'],'middleName'=>['nullable','string','max:100'],'lastName'=>['required','string','max:100'],'phone'=>['nullable','string','max:30'],'email'=>['nullable','email','max:255'],'employmentDate'=>['nullable','date'],'status'=>['required','in:active,inactive,retired']]);Teacher::updateOrCreate(['id'=>$teacher?->id],['school_id'=>$schoolId,'employee_id'=>$data['employeeId'],'first_name'=>$data['firstName'],'middle_name'=>$data['middleName']?:null,'last_name'=>$data['lastName'],'phone'=>$data['phone']?:null,'email'=>$data['email']?:null,'employment_date'=>$data['employmentDate']?:null,'status'=>$data['status']]);$this->showFormModal=false;$this->resetForm();LivewireAlert::title($teacher?'Teacher updated':'Teacher added')->success()->asToast()->position('top-end')->show();}catch(ValidationException $e){LivewireAlert::title('Check the form')->error()->asToast()->position('top-end')->show();throw $e;}catch(Throwable $e){report($e);LivewireAlert::title('Unable to save teacher')->error()->asToast()->position('top-end')->show();}}
    public function confirmDelete(Teacher $teacher):void{$this->authorize('delete',$teacher);$this->deletingId=$teacher->id;$this->showDeleteModal=true;}
    public function delete():void{$teacher=Teacher::findOrFail($this->deletingId);$this->authorize('delete',$teacher);if($teacher->classSubjects()->exists()||$teacher->classes()->exists()){$this->addError('delete','Teachers with class assignments must be marked inactive instead.');LivewireAlert::title('Teacher cannot be deleted')->warning()->asToast()->position('top-end')->show();return;}try{$teacher->delete();$this->showDeleteModal=false;$this->deletingId=null;LivewireAlert::title('Teacher archived')->success()->asToast()->position('top-end')->show();}catch(Throwable $e){report($e);LivewireAlert::title('Unable to archive teacher')->error()->asToast()->position('top-end')->show();}}
    public function closeModals():void{$this->showFormModal=false;$this->showDeleteModal=false;$this->resetForm();$this->resetErrorBag();}
    private function resetForm():void{$this->reset(['editingId','deletingId','employeeId','firstName','middleName','lastName','phone','email','employmentDate','status']);$this->status='active';$this->resetValidation();}
    public function render(){return view('livewire.lms.teachers.index',['teachers'=>Teacher::withCount(['classes','classSubjects'])->orderBy('last_name')->paginate(15)]);}
}
