<div class="space-y-6">
    <div><p class="text-xs font-semibold uppercase tracking-[.22em] text-slate-500">School schedule</p><h2 class="mt-2 text-2xl font-bold text-slate-900">My timetable</h2><p class="mt-1 text-sm text-slate-600">Your published class schedule, teachers, rooms, and lesson times.</p></div>

    <div class="grid grid-cols-3 gap-4">
        <article class="rounded-2xl border border-blue-100 bg-blue-50 p-5 shadow-sm"><p class="text-sm font-medium text-blue-800">Scheduled lessons</p><p class="mt-2 text-3xl font-bold text-blue-900">{{ $sessionCount }}</p><p class="mt-1 text-xs text-blue-700">Matching the current filters</p></article>
        <article class="rounded-2xl border border-violet-100 bg-violet-50 p-5 shadow-sm"><p class="text-sm font-medium text-violet-800">School days</p><p class="mt-2 text-3xl font-bold text-violet-900">{{ $dayCount }}</p><p class="mt-1 text-xs text-violet-700">Days represented in this schedule</p></article>
        <article class="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 shadow-sm"><p class="text-sm font-medium text-emerald-800">Subjects</p><p class="mt-2 text-3xl font-bold text-emerald-900">{{ $subjectCount }}</p><p class="mt-1 text-xs text-emerald-700">Distinct class-subject lessons</p></article>
    </div>

    <section class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="grid gap-3 lg:grid-cols-[minmax(0,1fr)_200px_260px_auto] lg:items-center">
        <div class="relative"><label for="student-timetable-search" class="sr-only">Search timetable</label><svg class="pointer-events-none absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-3.5-3.5"></path></svg><input id="student-timetable-search" type="search" wire:model.live.debounce.300ms="search" placeholder="Search subject, teacher, period, or room" class="w-full rounded-xl border-slate-300 py-2.5 pl-10 pr-24 text-sm shadow-sm focus:border-blue-700 focus:ring-blue-700"><span wire:loading wire:target="search" class="absolute right-3 top-1/2 -translate-y-1/2 text-xs font-medium text-slate-500">Searching...</span></div>
        <select wire:model.live="filterDay" aria-label="Filter by day" class="rounded-xl border-slate-300 py-2.5 text-sm shadow-sm focus:border-blue-700 focus:ring-blue-700"><option value="">All days</option>@foreach (App\Models\TimetableEntry::DAYS as $number => $day)<option value="{{ $number }}">{{ $day }}</option>@endforeach</select>
        <select wire:model.live="filterTermId" aria-label="Filter by term" class="rounded-xl border-slate-300 py-2.5 text-sm shadow-sm focus:border-blue-700 focus:ring-blue-700"><option value="">All terms</option>@foreach ($terms as $term)<option value="{{ $term->id }}">{{ $term->academicYear->name }} - {{ $term->name }}</option>@endforeach</select>
        @if (filled($search) || filled($filterDay) || filled($filterTermId))<x-button wire:click="clearFilters" variant="ghost" size="sm" target="clearFilters" :loading="true">Clear filters</x-button>@endif
    </div></section>

    <div class="flex justify-end"><x-ui.timetable-view-toggle :view-mode="$viewMode" /></div>

    @if ($viewMode === 'calendar')
        <x-ui.timetable-grid :entries="$gridEntries" :periods="$periods" :day-filter="$filterDay" :show-class="true" :show-teacher="true" :show-term="true" />
    @else
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm">
        <thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Day and time</th><th class="px-5 py-3">Subject</th><th class="px-5 py-3">Teacher</th><th class="px-5 py-3">Room</th><th class="px-5 py-3">Term</th></tr></thead>
        <tbody class="divide-y divide-slate-100">@forelse ($entries as $entry)<tr wire:key="student-entry-{{ $entry->id }}" class="hover:bg-slate-50/80"><td class="px-5 py-4"><p class="font-semibold text-slate-900">{{ $entry->dayName() }}</p><p class="mt-1 text-xs text-slate-500">{{ $entry->schedulePeriod->name }} &middot; {{ $entry->schedulePeriod->formattedStart() }}-{{ $entry->schedulePeriod->formattedEnd() }}</p></td><td class="px-5 py-4"><p class="font-semibold text-slate-900">{{ $entry->classSubject->subject->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $entry->schoolClass->name }}</p></td><td class="px-5 py-4 text-slate-700">{{ $entry->teacher ? $entry->teacher->first_name.' '.$entry->teacher->last_name : 'Not assigned' }}</td><td class="px-5 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-semibold {{ $entry->room ? 'bg-amber-100 text-amber-800' : 'bg-slate-100 text-slate-600' }}">{{ $entry->room ?: 'No room' }}</span></td><td class="px-5 py-4"><p class="text-slate-700">{{ $entry->timetable->term->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $entry->timetable->term->academicYear->name }}</p></td></tr>@empty<tr><td colspan="5" class="px-5 py-14 text-center text-slate-500">{{ filled($search) || filled($filterDay) || filled($filterTermId) ? 'No lessons match the current search and filters.' : 'No published timetable is available for your active class.' }}</td></tr>@endforelse</tbody>
    </table></div>@if ($entries->hasPages())<div class="border-t border-slate-200 px-5 py-4">{{ $entries->links() }}</div>@endif</div>
    @endif
</div>
