<?php
namespace App\Livewire\LMS\Topics\Concerns;
use App\Models\{ClassSubject,School,Topic}; use Illuminate\Database\Eloquent\Builder; use Illuminate\Foundation\Auth\Access\AuthorizesRequests; use Illuminate\Validation\{Rule,ValidationException}; use Jantinnerezo\LivewireAlert\Facades\LivewireAlert; use Livewire\Component; use Throwable;
abstract class ManagesTopics extends Component {
use AuthorizesRequests; public bool $showFormModal=false,$showDeleteModal=false; public ?int $editingId=null,$deletingId=null; public string $classSubjectId='',$title='',$description='',$sequence='0';
abstract protected function classSubjects():Builder; abstract protected function componentView():string;
public function create():void{$this->authorize('create',Topic::class);$this->resetForm();$this->showFormModal=true;}
public function edit(Topic $topic):void{$this->authorize('update',$topic);$this->managedClassSubject($topic->class_subject_id);$this->editingId=$topic->id;$this->classSubjectId=(string)$topic->class_subject_id;$this->title=$topic->title;$this->description=$topic->description??'';$this->sequence=(string)$topic->sequence;$this->showFormModal=true;}
public function save():void{$topic=$this->editingId?Topic::findOrFail($this->editingId):null;$this->authorize($topic?'update':'create',$topic??Topic::class);try{if($topic)$this->managedClassSubject($topic->class_subject_id);$data=$this->validate(['classSubjectId'=>['required','integer',Rule::exists('class_subjects','id')],'title'=>['required','string','max:255'],'description'=>['nullable','string','max:5000'],'sequence'=>['required','integer','min:0','max:9999']]);$classSubject=$this->managedClassSubject((int)$data['classSubjectId']);$duplicate=Topic::where('class_subject_id',$classSubject->id)->whereRaw('lower(title)=?',[mb_strtolower($data['title'])])->when($topic,fn($query)=>$query->whereKeyNot($topic->id))->exists();if($duplicate){$this->addError('title','This topic already exists for the selected class subject.');return;}Topic::updateOrCreate(['id'=>$topic?->id],['class_subject_id'=>$classSubject->id,'title'=>$data['title'],'description'=>$data['description']?:null,'sequence'=>$data['sequence']]);$this->showFormModal=false;$this->resetForm();LivewireAlert::title($topic?'Topic updated':'Topic created')->success()->asToast()->position('top-end')->show();}catch(ValidationException $e){LivewireAlert::title('Check the form')->error()->asToast()->position('top-end')->show();throw $e;}catch(Throwable $e){report($e);LivewireAlert::title('Unable to save topic')->error()->asToast()->position('top-end')->show();}}
public function confirmDelete(Topic $topic):void{$this->authorize('delete',$topic);$this->managedClassSubject($topic->class_subject_id);$this->deletingId=$topic->id;$this->showDeleteModal=true;} public function delete():void{$topic=Topic::findOrFail($this->deletingId);$this->authorize('delete',$topic);$this->managedClassSubject($topic->class_subject_id);try{$topic->delete();$this->showDeleteModal=false;$this->deletingId=null;LivewireAlert::title('Topic deleted')->success()->asToast()->position('top-end')->show();}catch(Throwable $e){report($e);LivewireAlert::title('Unable to delete topic')->error()->asToast()->position('top-end')->show();}}
public function closeModals():void{$this->showFormModal=false;$this->showDeleteModal=false;$this->resetForm();$this->resetErrorBag();} public function render(){$classSubjects=$this->classSubjects()->get();return view($this->componentView(),['topics'=>Topic::with(['classSubject.schoolClass','classSubject.subject'])->whereIn('class_subject_id',$classSubjects->pluck('id'))->withCount('lessons')->orderBy('sequence')->orderBy('title')->get(),'classSubjects'=>$classSubjects]);} protected function schoolId():int{return (int)School::query()->value('id');} protected function managedClassSubject(int $id):ClassSubject{return $this->classSubjects()->whereKey($id)->firstOrFail();} private function resetForm():void{$this->reset(['editingId','deletingId','classSubjectId','title','description','sequence']);$this->sequence='0';$this->resetValidation();}}
