<div class="space-y-6">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
        <div><p class="text-xs font-semibold uppercase tracking-[.22em] text-slate-500">Quiz building</p><h2 class="mt-2 text-2xl font-bold text-slate-900">{{ $quiz->title }}</h2><p class="mt-1 text-sm text-slate-600">Add and order questions. Correct answers remain server-side.</p></div>
        <div class="flex gap-3"><a href="{{ route(auth()->user()->hasRole('teacher') ? 'lms.quizzes.teacher.index' : 'lms.quizzes.admin.index') }}" class="inline-flex items-center rounded-xl bg-slate-100 px-4 py-2.5 text-sm font-semibold text-slate-800 hover:bg-slate-200">Back to quizzes</a><x-button wire:click="create" icon="plus" target="create">Add question</x-button></div>
    </div>
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-500"><tr><th class="px-5 py-3">Order</th><th class="px-5 py-3">Question</th><th class="px-5 py-3">Type</th><th class="px-5 py-3">Score</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($quizQuestions as $quizQuestion)<tr wire:key="quiz-question-{{ $quizQuestion->id }}"><td class="px-5 py-4">{{ $quizQuestion->sequence }}</td><td class="px-5 py-4">{{ Str::limit(strip_tags($quizQuestion->question->prompt),160) }}</td><td class="px-5 py-4">{{ str_replace('_',' ',ucfirst($quizQuestion->question->type)) }}</td><td class="px-5 py-4">{{ $quizQuestion->question->max_score }}</td><td class="px-5 py-4 text-right"><x-ui.icon-button wire:click="confirmDelete({{ $quizQuestion->id }})" icon="trash" label="Remove question" variant="danger" target="confirmDelete({{ $quizQuestion->id }})" /></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">No questions have been added to this quiz.</td></tr>@endforelse</tbody></table></div>
    <x-modal :show="$showFormModal" title="Add question to quiz" close-action="closeModals"><form wire:submit="save" class="space-y-5"><div><label for="questionId" class="block text-sm font-medium">Question</label><select wire:model.blur="questionId" id="questionId" class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Choose a question</option>@foreach($questions as $question)<option value="{{ $question->id }}">{{ Str::limit(strip_tags($question->prompt),100) }} — {{ $question->type }}</option>@endforeach</select>@error('questionId')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div><div><label for="sequence" class="block text-sm font-medium">Display order</label><input wire:model.blur="sequence" id="sequence" type="number" min="0" class="mt-1 block w-full rounded-lg border-slate-300">@error('sequence')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div><div class="flex justify-end gap-3"><x-button type="button" wire:click="closeModals" variant="secondary">Cancel</x-button><x-button type="submit" icon="save" target="save">Add question</x-button></div></form></x-modal>
    <x-modal :show="$showDeleteModal" title="Remove question?" close-action="closeModals" max-width="md"><p class="text-sm text-slate-600">This only removes the question from this quiz; the Question Bank entry is retained.</p><x-slot:footer><div class="flex justify-end gap-3"><x-button wire:click="closeModals" variant="secondary">Cancel</x-button><x-button wire:click="delete" variant="danger" icon="trash" target="delete">Remove</x-button></div></x-slot:footer></x-modal>
</div>
