<div class="space-y-6">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
        <div><p class="text-xs font-semibold uppercase tracking-[.22em] text-slate-500">Administration</p><h2 class="mt-2 text-2xl font-bold">Academic years</h2><p class="mt-1 text-sm text-slate-600">Create and manage school years while preserving historical records.</p></div>
        @can('create', App\Models\AcademicYear::class)<x-button wire:click="create" target="create" :loading="true" icon="plus">New year</x-button>@endcan
    </div>
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-left text-sm"><thead class="bg-slate-50 text-slate-600"><tr><th class="px-5 py-3">Year</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Terms</th><th class="px-5 py-3">Date range</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-200">@forelse($years as $year)<tr wire:key="academic-year-{{ $year->id }}"><td class="px-5 py-4 font-medium">{{ $year->name }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $year->is_active?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-600' }}">{{ $year->is_active?'Active':'Inactive' }}</span></td><td class="px-5 py-4">{{ $year->terms_count }}</td><td class="px-5 py-4">{{ $year->starts_at->format('M d, Y') }} – {{ $year->ends_at->format('M d, Y') }}</td><td class="px-5 py-4"><div class="flex justify-end gap-2">@can('update',$year)<x-ui.icon-button wire:click="edit({{ $year->id }})" icon="edit" label="Edit {{ $year->name }}" target="edit({{ $year->id }})" />@endcan @can('delete',$year)<x-ui.icon-button wire:click="confirmDelete({{ $year->id }})" icon="trash" variant="danger" label="Delete {{ $year->name }}" target="confirmDelete({{ $year->id }})" />@endcan</div></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">No academic years yet. Create your first one.</td></tr>@endforelse</tbody></table></div></div>

    <x-modal :show="$showFormModal" :title="$editingId ? 'Edit academic year' : 'New academic year'" close-action="closeModals">
        <form wire:submit="save" class="space-y-5"><div><label for="year-name" class="block text-sm font-medium">Academic year</label><input wire:model.blur="name" id="year-name" type="text" placeholder="2026/2027" class="mt-1 block w-full rounded-lg border-slate-300 shadow-sm">@error('name')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div><div class="grid gap-5 sm:grid-cols-2"><div><label for="starts-at" class="block text-sm font-medium">Start date</label><input wire:model.blur="startsAt" id="starts-at" type="date" class="mt-1 block w-full rounded-lg border-slate-300 shadow-sm">@error('startsAt')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div><div><label for="ends-at" class="block text-sm font-medium">End date</label><input wire:model.blur="endsAt" id="ends-at" type="date" class="mt-1 block w-full rounded-lg border-slate-300 shadow-sm">@error('endsAt')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div></div><label class="flex items-center gap-3 rounded-lg bg-slate-50 p-3 text-sm"><input wire:model="isActive" type="checkbox" class="rounded border-slate-300 text-blue-700"> Set as the active academic year</label><div class="flex justify-end gap-3 pt-2"><x-button wire:click="closeModals" type="button" variant="ghost" target="closeModals" :loading="true">Cancel</x-button><x-button type="submit" icon="save" target="save" :loading="true">Save academic year</x-button></div></form>
    </x-modal>

    <x-modal :show="$showDeleteModal" title="Delete academic year?" close-action="closeModals" max-width="md">
        <p class="text-sm text-slate-600">Only inactive years with no terms or classes can be deleted.</p>@error('delete')<p class="mt-3 text-sm text-rose-700">{{ $message }}</p>@enderror
        <x-slot:footer><div class="flex justify-end gap-3"><x-button wire:click="closeModals" variant="ghost" target="closeModals" :loading="true">Cancel</x-button><x-button wire:click="delete" variant="danger" icon="trash" target="delete" :loading="true">Delete year</x-button></div></x-slot:footer>
    </x-modal>
</div>
