<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('schools', function(Blueprint $t){$t->id();$t->string('name');$t->string('code')->unique();$t->string('motto')->nullable();$t->string('email')->nullable();$t->string('phone')->nullable();$t->text('address')->nullable();$t->string('logo_path')->nullable();$t->timestamps();});
  Schema::create('academic_years', function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('name');$t->date('starts_at');$t->date('ends_at');$t->boolean('is_active')->default(false);$t->boolean('is_locked')->default(false);$t->timestamps();$t->unique(['school_id','name']);$t->index(['school_id','is_active']);});
  Schema::create('terms', function(Blueprint $t){$t->id();$t->foreignId('academic_year_id')->constrained()->cascadeOnDelete();$t->string('name');$t->unsignedTinyInteger('sequence')->default(1);$t->date('starts_at');$t->date('ends_at');$t->boolean('is_active')->default(false);$t->boolean('is_locked')->default(false);$t->timestamps();$t->unique(['academic_year_id','name']);$t->index(['academic_year_id','is_active']);});
  Schema::create('streams', function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('description')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['school_id','name']);});
  Schema::create('school_classes', function(Blueprint $t){$t->id();$t->foreignId('academic_year_id')->constrained()->cascadeOnDelete();$t->foreignId('stream_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('code')->nullable();$t->string('status')->default('active');$t->timestamps();$t->unique(['academic_year_id','name','stream_id']);$t->index(['academic_year_id','status']);});
  Schema::create('subjects', function(Blueprint $t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('code')->nullable();$t->text('description')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['school_id','code']);$t->index(['school_id','is_active']);});
  Schema::create('students', function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->unique()->constrained()->nullOnDelete();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('student_id')->unique();$t->string('admission_number')->unique();$t->string('first_name');$t->string('middle_name')->nullable();$t->string('last_name');$t->date('date_of_birth');$t->string('gender',20);$t->string('photo_path')->nullable();$t->date('admission_date');$t->string('status')->default('active');$t->softDeletes();$t->timestamps();$t->index(['school_id','status']);});
  Schema::create('teachers', function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->unique()->constrained()->nullOnDelete();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('employee_id')->unique();$t->string('first_name');$t->string('middle_name')->nullable();$t->string('last_name');$t->string('photo_path')->nullable();$t->string('phone')->nullable();$t->string('email')->nullable();$t->date('employment_date')->nullable();$t->string('status')->default('active');$t->softDeletes();$t->timestamps();$t->index(['school_id','status']);});
  Schema::create('parents', function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->unique()->constrained()->nullOnDelete();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('first_name');$t->string('last_name');$t->string('phone')->nullable();$t->string('email')->nullable();$t->text('address')->nullable();$t->softDeletes();$t->timestamps();});
  Schema::create('class_enrollments', function(Blueprint $t){$t->id();$t->foreignId('school_class_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->date('enrolled_at');$t->date('left_at')->nullable();$t->string('status')->default('active');$t->timestamps();$t->unique(['school_class_id','student_id']);$t->index(['student_id','status']);});
  Schema::create('class_subjects', function(Blueprint $t){$t->id();$t->foreignId('school_class_id')->constrained()->cascadeOnDelete();$t->foreignId('subject_id')->constrained()->cascadeOnDelete();$t->foreignId('teacher_id')->nullable()->constrained()->nullOnDelete();$t->timestamps();$t->unique(['school_class_id','subject_id']);$t->index('teacher_id');});
  Schema::create('class_teachers', function(Blueprint $t){$t->id();$t->foreignId('school_class_id')->constrained()->cascadeOnDelete();$t->foreignId('teacher_id')->constrained()->cascadeOnDelete();$t->string('role')->default('teacher');$t->timestamps();$t->unique(['school_class_id','teacher_id']);});
  Schema::create('parent_student', function(Blueprint $t){$t->id();$t->foreignId('parent_id')->constrained('parents')->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->string('relationship')->nullable();$t->boolean('is_primary_contact')->default(false);$t->timestamps();$t->unique(['parent_id','student_id']);});
 }
 public function down():void{foreach(['parent_student','class_teachers','class_subjects','class_enrollments','parents','teachers','students','subjects','school_classes','streams','terms','academic_years','schools'] as $table)Schema::dropIfExists($table);}
};
