<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void {
  Schema::create('assessment_components',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('term_id')->constrained()->cascadeOnDelete();$t->string('name');$t->decimal('weight',5,2);$t->unsignedInteger('sequence')->default(0);$t->timestamps();$t->unique(['term_id','name']);}));
  Schema::create('assessments',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('class_subject_id')->constrained()->cascadeOnDelete();$t->foreignId('term_id')->constrained()->cascadeOnDelete();$t->foreignId('assessment_component_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('teacher_id')->constrained()->cascadeOnDelete();$t->string('title');$t->decimal('max_score',8,2)->default(100);$t->date('assessed_at');$t->string('status')->default('draft');$t->timestamps();$t->index(['class_subject_id','term_id','status']);}));
  Schema::create('assessment_scores',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('assessment_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->decimal('score',8,2)->nullable();$t->longText('comment')->nullable();$t->timestamps();$t->unique(['assessment_id','student_id']);$t->index('student_id');}));
  Schema::create('grading_scales',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('grade');$t->decimal('minimum',5,2);$t->decimal('maximum',5,2);$t->string('remark')->nullable();$t->unsignedInteger('sequence')->default(0);$t->timestamps();$t->unique(['school_id','grade']);}));
  Schema::create('subject_results',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->foreignId('class_subject_id')->constrained()->cascadeOnDelete();$t->foreignId('term_id')->constrained()->cascadeOnDelete();$t->decimal('total_score',8,2)->nullable();$t->foreignId('grading_scale_id')->nullable()->constrained()->nullOnDelete();$t->string('grade')->nullable();$t->longText('teacher_comment')->nullable();$t->string('status')->default('draft');$t->timestamps();$t->unique(['student_id','class_subject_id','term_id']);$t->index(['student_id','term_id','status']);}));
  Schema::create('report_cards',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->foreignId('academic_year_id')->constrained()->cascadeOnDelete();$t->foreignId('term_id')->constrained()->cascadeOnDelete();$t->foreignId('school_class_id')->constrained()->cascadeOnDelete();$t->longText('teacher_comment')->nullable();$t->longText('headteacher_comment')->nullable();$t->decimal('attendance_percentage',5,2)->nullable();$t->string('status')->default('draft');$t->string('pdf_path')->nullable();$t->timestamp('generated_at')->nullable();$t->timestamp('published_at')->nullable();$t->timestamps();$t->unique(['student_id','term_id']);$t->index(['school_class_id','term_id','status']);}));
  Schema::create('attendance_records',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('academic_year_id')->constrained()->cascadeOnDelete();$t->foreignId('term_id')->constrained()->cascadeOnDelete();$t->foreignId('school_class_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->date('attendance_date');$t->string('status');$t->text('remarks')->nullable();$t->foreignId('marked_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['student_id','school_class_id','attendance_date']);$t->index(['student_id','term_id','attendance_date']);$t->index(['school_class_id','attendance_date']);}));
  Schema::create('schedule_periods',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('name');$t->time('starts_at');$t->time('ends_at');$t->unsignedInteger('sequence')->default(0);$t->timestamps();}));
  Schema::create('timetables',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('academic_year_id')->constrained()->cascadeOnDelete();$t->foreignId('term_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('status')->default('draft');$t->timestamps();$t->unique(['academic_year_id','term_id','name']);}));
  Schema::create('timetable_entries',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('timetable_id')->constrained()->cascadeOnDelete();$t->foreignId('school_class_id')->constrained()->cascadeOnDelete();$t->foreignId('class_subject_id')->constrained()->cascadeOnDelete();$t->foreignId('teacher_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('schedule_period_id')->constrained()->cascadeOnDelete();$t->unsignedTinyInteger('day_of_week');$t->string('room')->nullable();$t->timestamps();$t->unique(['timetable_id','school_class_id','day_of_week','schedule_period_id']);$t->index(['timetable_id','teacher_id','day_of_week','schedule_period_id']);}));
  Schema::create('announcements',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->foreignId('school_class_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('subject_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('created_by')->constrained('users')->cascadeOnDelete();$t->string('title');$t->longText('content');$t->string('audience')->default('school');$t->timestamp('published_at')->nullable();$t->timestamp('expires_at')->nullable();$t->timestamps();$t->softDeletes();$t->index(['school_id','published_at']);}));
  Schema::create('school_settings',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('school_id')->constrained()->cascadeOnDelete();$t->string('key');$t->json('value')->nullable();$t->timestamps();$t->unique(['school_id','key']);}));
 }
 public function down():void{foreach(['school_settings','announcements','timetable_entries','timetables','schedule_periods','attendance_records','report_cards','subject_results','grading_scales','assessment_scores','assessments','assessment_components'] as $table)Schema::dropIfExists($table);}
};
