<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('topics',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('class_subject_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('description')->nullable();$t->unsignedInteger('sequence')->default(0);$t->timestamps();$t->index(['class_subject_id','sequence']);}));
  Schema::create('lessons',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('topic_id')->constrained()->cascadeOnDelete();$t->foreignId('teacher_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('summary')->nullable();$t->longText('content')->nullable();$t->json('objectives')->nullable();$t->unsignedInteger('sequence')->default(0);$t->string('status')->default('draft');$t->timestamp('published_at')->nullable();$t->softDeletes();$t->timestamps();$t->index(['topic_id','status','sequence']);}));
  Schema::create('lesson_resources',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('lesson_id')->constrained()->cascadeOnDelete();$t->string('title');$t->string('type');$t->string('disk')->default('private');$t->string('path')->nullable();$t->string('external_url')->nullable();$t->unsignedBigInteger('size')->nullable();$t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();}));
  Schema::create('lesson_progress',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('lesson_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->timestamp('completed_at')->nullable();$t->timestamps();$t->unique(['lesson_id','student_id']);$t->index('student_id');}));
  Schema::create('assignments',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('class_subject_id')->constrained()->cascadeOnDelete();$t->foreignId('topic_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('lesson_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('teacher_id')->constrained()->cascadeOnDelete();$t->string('title');$t->longText('instructions');$t->decimal('max_score',8,2)->default(100);$t->timestamp('opens_at')->nullable();$t->timestamp('due_at');$t->boolean('allow_late_submission')->default(false);$t->string('status')->default('draft');$t->softDeletes();$t->timestamps();$t->index(['class_subject_id','status','due_at']);}));
  Schema::create('assignment_attachments',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('assignment_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('disk')->default('private');$t->string('path');$t->unsignedBigInteger('size')->nullable();$t->timestamps();}));
  Schema::create('assignment_submissions',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('assignment_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->longText('submission_text')->nullable();$t->string('status')->default('draft');$t->timestamp('submitted_at')->nullable();$t->decimal('score',8,2)->nullable();$t->longText('feedback')->nullable();$t->foreignId('graded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('graded_at')->nullable();$t->timestamps();$t->unique(['assignment_id','student_id']);$t->index(['student_id','status']);}));
  Schema::create('submission_attachments',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('assignment_submission_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('disk')->default('private');$t->string('path');$t->unsignedBigInteger('size')->nullable();$t->timestamps();}));
  Schema::create('quizzes',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('class_subject_id')->constrained()->cascadeOnDelete();$t->foreignId('topic_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('lesson_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('teacher_id')->constrained()->cascadeOnDelete();$t->string('title');$t->longText('instructions')->nullable();$t->unsignedSmallInteger('time_limit_minutes')->nullable();$t->decimal('pass_mark',5,2)->nullable();$t->unsignedSmallInteger('max_attempts')->default(1);$t->boolean('randomize_questions')->default(false);$t->timestamp('opens_at')->nullable();$t->timestamp('closes_at')->nullable();$t->string('status')->default('draft');$t->softDeletes();$t->timestamps();$t->index(['class_subject_id','status','opens_at']);}));
  Schema::create('questions',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->string('type');$t->longText('prompt');$t->json('grading_key')->nullable();$t->decimal('max_score',8,2)->default(1);$t->timestamps();}));
  Schema::create('quiz_questions',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('quiz_id')->constrained()->cascadeOnDelete();$t->foreignId('question_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('sequence')->default(0);$t->timestamps();$t->unique(['quiz_id','question_id']);$t->index(['quiz_id','sequence']);}));
  Schema::create('question_options',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('question_id')->constrained()->cascadeOnDelete();$t->longText('label');$t->boolean('is_correct')->default(false);$t->unsignedInteger('sequence')->default(0);$t->timestamps();$t->index(['question_id','sequence']);}));
  Schema::create('quiz_attempts',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('quiz_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->unsignedSmallInteger('attempt_number');$t->timestamp('started_at');$t->timestamp('submitted_at')->nullable();$t->decimal('score',8,2)->nullable();$t->string('status')->default('in_progress');$t->timestamps();$t->unique(['quiz_id','student_id','attempt_number']);$t->index(['student_id','status']);}));
  Schema::create('quiz_answers',fn(Blueprint $t)=>tap($t,function($t){$t->id();$t->foreignId('quiz_attempt_id')->constrained()->cascadeOnDelete();$t->foreignId('question_id')->constrained()->cascadeOnDelete();$t->json('answer')->nullable();$t->decimal('score',8,2)->nullable();$t->longText('feedback')->nullable();$t->foreignId('graded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('graded_at')->nullable();$t->timestamps();$t->unique(['quiz_attempt_id','question_id']);}));
 }
 public function down():void{foreach(['quiz_answers','quiz_attempts','question_options','quiz_questions','questions','quizzes','submission_attachments','assignment_submissions','assignment_attachments','assignments','lesson_progress','lesson_resources','lessons','topics'] as $table)Schema::dropIfExists($table);}
};
