<div class="space-y-6">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
        <div><p class="text-xs font-semibold uppercase tracking-[.22em] text-slate-500">Curriculum</p><h2 class="mt-2 text-2xl font-bold text-slate-900">Topics</h2><p class="mt-1 text-sm text-slate-600">Organize each class subject into a clear teaching sequence.</p></div>
        @can('create', App\Models\Topic::class)<x-button wire:click="create" variant="primary" icon="plus" target="create">New topic</x-button>@endcan
    </div>
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm">
        <thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Topic</th><th class="px-5 py-3">Class subject</th><th class="px-5 py-3">Order</th><th class="px-5 py-3">Lessons</th><th class="px-5 py-3 text-right">Actions</th></tr></thead>
        <tbody class="divide-y divide-slate-100">@forelse($topics as $topic)<tr wire:key="topic-{{ $topic->id }}"><td class="px-5 py-4"><p class="font-medium text-slate-900">{{ $topic->title }}</p>@if($topic->description)<p class="mt-1 max-w-lg truncate text-xs text-slate-500">{{ $topic->description }}</p>@endif</td><td class="px-5 py-4 text-slate-700">{{ $topic->classSubject->schoolClass->name }} · {{ $topic->classSubject->subject->name }}</td><td class="px-5 py-4 text-slate-700">{{ $topic->sequence }}</td><td class="px-5 py-4 text-slate-700">{{ $topic->lessons_count }}</td><td class="px-5 py-4"><div class="flex justify-end gap-2">@can('update', $topic)<x-ui.icon-button wire:click="edit({{ $topic->id }})" icon="edit" label="Edit topic" target="edit({{ $topic->id }})" />@endcan @can('delete', $topic)<x-ui.icon-button wire:click="confirmDelete({{ $topic->id }})" icon="trash" label="Delete topic" variant="danger" target="confirmDelete({{ $topic->id }})" />@endcan</div></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">No topics yet. Create a class subject allocation first, then add its teaching topics.</td></tr>@endforelse</tbody>
    </table></div></div>
    <x-modal :show="$showFormModal" :title="$editingId ? 'Edit topic' : 'New topic'" close-action="closeModals">
        <form wire:submit="save" class="space-y-5">
            <div><label for="classSubjectId" class="block text-sm font-medium text-slate-700">Class subject</label><select wire:model.blur="classSubjectId" id="classSubjectId" class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Choose a class subject</option>@foreach($classSubjects as $classSubject)<option value="{{ $classSubject->id }}">{{ $classSubject->schoolClass->name }} — {{ $classSubject->subject->name }}</option>@endforeach</select>@error('classSubjectId')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
            <div><label for="title" class="block text-sm font-medium text-slate-700">Topic title</label><input wire:model.blur="title" id="title" class="mt-1 block w-full rounded-lg border-slate-300">@error('title')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
            <div><label for="description" class="block text-sm font-medium text-slate-700">Description <span class="text-slate-400">(optional)</span></label><textarea wire:model.blur="description" id="description" rows="4" class="mt-1 block w-full rounded-lg border-slate-300"></textarea>@error('description')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
            <div><label for="sequence" class="block text-sm font-medium text-slate-700">Teaching order</label><input wire:model.blur="sequence" id="sequence" type="number" min="0" class="mt-1 block w-full rounded-lg border-slate-300">@error('sequence')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
            <div class="flex justify-end gap-3"><x-button type="button" wire:click="closeModals" variant="secondary" icon="close" target="closeModals">Cancel</x-button><x-button type="submit" variant="primary" icon="save" target="save">Save topic</x-button></div>
        </form>
    </x-modal>
    <x-modal :show="$showDeleteModal" title="Delete topic?" close-action="closeModals" max-width="md"><p class="text-sm text-slate-600">Deleting this topic also removes its lessons and resources. This cannot be undone.</p><x-slot:footer><div class="flex justify-end gap-3"><x-button wire:click="closeModals" variant="secondary" icon="close" target="closeModals">Cancel</x-button><x-button wire:click="delete" variant="danger" icon="trash" target="delete">Delete topic</x-button></div></x-slot:footer></x-modal>
</div>
