<div class="space-y-6">
    <header class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
        <p class="text-xs font-bold uppercase tracking-[.22em] text-blue-700">Communication</p>
        <div class="mt-2 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
            <div><h1 class="text-2xl font-bold text-slate-900 sm:text-3xl">SMS Centre</h1><p class="mt-2 max-w-3xl text-sm text-slate-600">Send a private message or a school-scoped SMS campaign. Delivery continues in the background.</p></div>
            <div class="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">Gateway: <span class="font-bold">{{ ucfirst((string) config('sms.default', 'log')) }}</span><p class="text-xs text-amber-800">Keep the <span class="font-semibold">{{ config('sms.queue', 'sms') }}</span> queue worker running.</p></div>
        </div>
    </header>

    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <x-stat-card label="SMS campaigns" :value="number_format($stats['campaigns'])" tone="primary" />
        <x-stat-card label="Delivered messages" :value="number_format($stats['delivered'])" tone="success" />
        <x-stat-card label="Queued or processing" :value="number_format($stats['processing'])" tone="warning" />
        <x-stat-card label="Failed deliveries" :value="number_format($stats['failed'])" tone="danger" />
    </section>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div class="border-b border-slate-200 bg-slate-50 px-5 py-4 sm:px-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-lg font-bold text-slate-900">Compose an SMS</h2><p class="mt-1 text-sm text-slate-500">Recipients are resolved again when the campaign is queued.</p></div><div class="inline-flex rounded-xl border border-slate-200 bg-white p-1"><button type="button" wire:click="setMode('bulk')" class="rounded-lg px-4 py-2 text-sm font-semibold {{ $mode === 'bulk' ? 'bg-blue-900 text-white' : 'text-slate-600 hover:bg-slate-100' }}">Bulk SMS</button><button type="button" wire:click="setMode('single')" class="rounded-lg px-4 py-2 text-sm font-semibold {{ $mode === 'single' ? 'bg-blue-900 text-white' : 'text-slate-600 hover:bg-slate-100' }}">Single SMS</button></div></div></div>
        <form wire:submit="reviewRecipients" class="space-y-6 p-5 sm:p-6">
            @if ($mode === 'bulk')
                <div class="grid gap-5 lg:grid-cols-2"><fieldset><legend class="text-sm font-bold text-slate-800">Recipient groups</legend><div class="mt-3 grid gap-3 sm:grid-cols-3">@foreach (['staff' => 'Staff', 'parents' => 'Parents', 'students' => 'Students'] as $value => $label)<label class="flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" value="{{ $value }}" wire:model.live="audiences" class="rounded border-slate-300 text-blue-900">{{ $label }}</label>@endforeach</div>@error('audiences')<p class="mt-2 text-sm text-rose-700">{{ $message }}</p>@enderror</fieldset><div><label for="sms-class" class="text-sm font-bold text-slate-800">Class filter <span class="font-normal text-slate-400">(optional)</span></label><select id="sms-class" wire:model.live="classId" class="mt-3 block w-full rounded-xl border-slate-300 text-sm"><option value="">All current classes</option>@foreach ($classes as $class)<option value="{{ $class->id }}">{{ $class->name }}{{ $class->stream ? ' · '.$class->stream->name : '' }} — {{ $class->academicYear?->name }}</option>@endforeach</select>@error('classId')<p class="mt-2 text-sm text-rose-700">{{ $message }}</p>@enderror</div></div>
            @else
                <div><label for="sms-search" class="text-sm font-bold text-slate-800">Find a recipient</label><input id="sms-search" type="search" wire:model.live.debounce.300ms="recipientSearch" placeholder="Name, ID, email, or phone" class="mt-2 block w-full rounded-xl border-slate-300 text-sm"><label for="sms-recipient" class="mt-4 block text-sm font-bold text-slate-800">Recipient</label><select id="sms-recipient" wire:model.live="singleRecipientKey" class="mt-2 block w-full rounded-xl border-slate-300 text-sm"><option value="">Choose a recipient</option>@foreach ($candidates as $candidate)<option value="{{ $candidate['key'] }}" @disabled(! $candidate['sendable'])>{{ $candidate['name'] }} · {{ ucfirst($candidate['audience']) }} · {{ $candidate['phone'] ?: 'No mobile number' }}</option>@endforeach</select>@error('singleRecipientKey')<p class="mt-2 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
            @endif
            <div><label for="sms-message" class="block text-sm font-bold text-slate-800">Message</label><textarea id="sms-message" wire:model.live="message" rows="6" maxlength="1530" placeholder="Write your SMS message..." class="mt-2 block w-full rounded-xl border-slate-300 text-sm"></textarea><div class="mt-1 flex justify-between text-xs text-slate-500"><span>@error('message')<span class="font-medium text-rose-700">{{ $message }}</span>@enderror</span><span>{{ $messageMetrics['characters'] }}/1530 · {{ $messageMetrics['segments'] }} segment{{ $messageMetrics['segments'] === 1 ? '' : 's' }}</span></div></div>
            <div class="flex flex-col-reverse gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end"><x-button type="button" wire:click="clearComposer" variant="ghost" icon="close">Clear</x-button><x-button type="submit" icon="check" target="reviewRecipients" :loading="true">Review recipients</x-button></div>
        </form>
    </section>

    <section class="space-y-4"><div><h2 class="text-xl font-bold text-slate-900">Delivery history</h2><p class="mt-1 text-sm text-slate-500">Track delivery progress and retry failed messages.</p></div><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="grid gap-3 sm:grid-cols-[1fr_220px_auto]"><input type="search" wire:model.live.debounce.300ms="historySearch" placeholder="Search message or sender" class="rounded-xl border-slate-300 text-sm"><select wire:model.live="historyStatus" aria-label="Filter delivery status" class="rounded-xl border-slate-300 text-sm"><option value="">All statuses</option><option value="queued">Queued</option><option value="processing">Processing</option><option value="completed">Completed</option><option value="partial">Partial</option><option value="failed">Failed</option></select>@if ($historySearch || $historyStatus)<x-button wire:click="clearHistoryFilters" variant="ghost">Clear</x-button>@endif</div></div>
        <div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm">
            <table class="min-w-full divide-y divide-slate-200 text-sm">
                <thead class="bg-slate-50 text-left text-xs font-bold uppercase text-slate-500"><tr><th class="px-5 py-3">Message</th><th class="px-5 py-3">Audience</th><th class="px-5 py-3">Delivery</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Queued</th><th class="px-5 py-3 text-right">Actions</th></tr></thead>
                <tbody class="divide-y divide-slate-100">
                    @forelse ($campaigns as $campaign)
                        <tr>
                            <td class="px-5 py-4"><p class="max-w-sm font-semibold text-slate-900">{{ str($campaign->message)->limit(90) }}</p><p class="mt-1 text-xs text-slate-500">By {{ $campaign->creator?->name ?: 'Deleted user' }} · {{ ucfirst($campaign->mode) }}</p></td>
                            <td class="px-5 py-4 text-xs text-slate-600">{{ collect($campaign->audiences)->map(fn ($audience) => ucfirst($audience))->implode(', ') }}</td>
                            <td class="px-5 py-4 text-xs text-slate-600"><span class="font-bold text-emerald-700">{{ number_format($campaign->sent_count) }}</span> / {{ number_format($campaign->recipient_count) }} sent @if ($campaign->failed_count)<p class="text-rose-700">{{ number_format($campaign->failed_count) }} failed</p>@endif</td>
                            <td class="px-5 py-4"><x-badge :variant="in_array($campaign->status, ['queued', 'processing', 'partial'], true) ? 'warning' : ($campaign->status === 'completed' ? 'success' : 'danger')">{{ str($campaign->status)->headline() }}</x-badge></td>
                            <td class="whitespace-nowrap px-5 py-4 text-xs text-slate-500">{{ $campaign->queued_at?->format('d M Y H:i') }}</td>
                            <td class="px-5 py-4"><div class="flex justify-end gap-2"><x-button wire:click="viewCampaign({{ $campaign->id }})" variant="ghost" size="xs">Details</x-button>@if ($campaign->failed_count > 0)<x-button wire:click="confirmRetry({{ $campaign->id }})" variant="secondary" size="xs">Retry failed</x-button>@endif</div></td>
                        </tr>
                    @empty
                        <tr><td colspan="6" class="px-6 py-14 text-center text-slate-500">No SMS campaigns match the current filters.</td></tr>
                    @endforelse
                </tbody>
            </table>
            @if ($campaigns->hasPages())<div class="border-t border-slate-200 px-5 py-4">{{ $campaigns->links() }}</div>@endif
        </div>
    </section>

    <x-modal :show="$showReviewModal" title="Review and queue SMS" close-action="closeModals" max-width="2xl"><div class="space-y-5"><div class="rounded-xl border border-blue-200 bg-blue-50 p-4"><p class="text-sm font-bold text-blue-950">{{ $message }}</p><div class="mt-3 grid grid-cols-3 gap-3"><div><p class="text-xs font-semibold text-blue-700">Deliverable</p><p class="text-2xl font-bold text-blue-950">{{ number_format($previewRecipientCount) }}</p></div><div><p class="text-xs font-semibold text-blue-700">Missing</p><p class="text-2xl font-bold text-blue-950">{{ number_format($previewMissingCount) }}</p></div><div><p class="text-xs font-semibold text-blue-700">Duplicates</p><p class="text-2xl font-bold text-blue-950">{{ number_format($previewDuplicateCount) }}</p></div></div></div><div class="max-h-72 divide-y divide-slate-100 overflow-y-auto rounded-xl border border-slate-200">@foreach ($previewSample as $recipient)<div class="flex justify-between gap-3 px-4 py-3 text-sm"><div><p class="font-semibold">{{ $recipient['name'] }}</p><p class="text-xs text-slate-500">{{ $recipient['phone'] }}</p></div><x-badge variant="info">{{ ucfirst($recipient['audience']) }}</x-badge></div>@endforeach</div></div><x-slot:footer><div class="flex justify-end gap-3"><x-button wire:click="closeModals" variant="secondary">Go back</x-button><x-button wire:click="queueSms" variant="success" target="queueSms" :loading="true">Queue {{ number_format($previewRecipientCount) }} SMS</x-button></div></x-slot:footer></x-modal>
    <x-modal :show="$showDetailsModal" title="Campaign delivery details" close-action="closeModals" max-width="3xl">@if ($detailsCampaign)<div class="space-y-4"><div class="flex justify-between"><h3 class="font-bold">{{ $detailsCampaign->message }}</h3><x-badge variant="info">{{ str($detailsCampaign->status)->headline() }}</x-badge></div><div class="max-h-96 overflow-auto rounded-xl border"><table class="min-w-full text-sm"><tbody class="divide-y">@foreach ($detailsRecipients as $recipient)<tr><td class="px-4 py-3">{{ $recipient->recipient_name }}<p class="text-xs text-slate-500">{{ $recipient->phone }}</p></td><td class="px-4 py-3">{{ ucfirst($recipient->audience) }}</td><td class="px-4 py-3">{{ ucfirst($recipient->status) }}</td><td class="px-4 py-3 text-xs">{{ $recipient->last_error ?: $recipient->skip_reason }}</td></tr>@endforeach</tbody></table></div></div>@endif<x-slot:footer><x-button wire:click="closeModals" variant="secondary">Close</x-button></x-slot:footer></x-modal>
    <x-modal :show="$showRetryModal" title="Retry failed deliveries?" close-action="closeModals" max-width="md"><p class="text-sm text-slate-600">Only failed recipients will be queued again.</p><x-slot:footer><div class="flex justify-end gap-3"><x-button wire:click="closeModals" variant="secondary">Cancel</x-button><x-button wire:click="retryFailed" variant="primary" target="retryFailed" :loading="true">Queue failed again</x-button></div></x-slot:footer></x-modal>
</div>
