<div class="space-y-6">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p class="text-xs font-semibold uppercase tracking-[.22em] text-slate-500">Curriculum</p><h2 class="mt-2 text-2xl font-bold text-slate-900">{{ $heading }}</h2><p class="mt-1 text-sm text-slate-600">{{ $description }}</p></div><x-button wire:click="create" variant="primary" icon="plus" target="create">New lesson</x-button></div>
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Lesson</th><th class="px-5 py-3">Class subject</th><th class="px-5 py-3">Teacher</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($lessons as $lesson)<tr wire:key="lesson-{{ $lesson->id }}"><td class="px-5 py-4"><p class="font-medium text-slate-900">{{ $lesson->sequence }}. {{ $lesson->title }}</p><p class="mt-1 max-w-md truncate text-xs text-slate-500">{{ $lesson->summary ?: 'No summary' }}</p></td><td class="px-5 py-4 text-slate-700">{{ $lesson->topic->classSubject->schoolClass->name }} · {{ $lesson->topic->classSubject->subject->name }}<span class="block text-xs text-slate-500">{{ $lesson->topic->title }}</span></td><td class="px-5 py-4 text-slate-700">{{ $lesson->teacher->first_name }} {{ $lesson->teacher->last_name }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $lesson->status==='published'?'bg-emerald-100 text-emerald-700':($lesson->status==='archived'?'bg-slate-100 text-slate-600':'bg-amber-100 text-amber-700') }}">{{ ucfirst($lesson->status) }}</span></td><td class="px-5 py-4"><div class="flex justify-end gap-2">@can('update',$lesson)<x-ui.icon-button wire:click="edit({{ $lesson->id }})" icon="edit" label="Edit lesson" target="edit({{ $lesson->id }})" />@endcan @can('delete',$lesson)<x-ui.icon-button wire:click="confirmDelete({{ $lesson->id }})" icon="trash" label="Archive lesson" variant="danger" target="confirmDelete({{ $lesson->id }})" />@endcan</div></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">No lessons yet. Create a topic first, then add its lesson plan.</td></tr>@endforelse</tbody></table></div></div>
    <x-modal :show="$showFormModal" :title="$editingId?'Edit lesson':'New lesson'" close-action="closeModals" max-width="xl"><form wire:submit="save" class="space-y-5">
        <div class="grid gap-5 sm:grid-cols-2"><div><label for="topicId" class="block text-sm font-medium text-slate-700">Topic</label><select wire:model.blur="topicId" id="topicId" class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Choose a topic</option>@foreach($topics as $topic)<option value="{{ $topic->id }}">{{ $topic->classSubject->schoolClass->name }} · {{ $topic->classSubject->subject->name }} — {{ $topic->title }}</option>@endforeach</select>@error('topicId')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
        @if($canChooseTeacher)<div><label for="teacherId" class="block text-sm font-medium text-slate-700">Teacher <span class="text-slate-400">(uses class subject teacher by default)</span></label><select wire:model.blur="teacherId" id="teacherId" class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Use class subject teacher</option>@foreach($teachers as $teacher)<option value="{{ $teacher->id }}">{{ $teacher->first_name }} {{ $teacher->last_name }}</option>@endforeach</select>@error('teacherId')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>@endif</div>
        <div class="grid gap-5 sm:grid-cols-2"><div><label for="title" class="block text-sm font-medium text-slate-700">Lesson title</label><input wire:model.blur="title" id="title" class="mt-1 block w-full rounded-lg border-slate-300">@error('title')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div><div><label for="sequence" class="block text-sm font-medium text-slate-700">Teaching order</label><input wire:model.blur="sequence" id="sequence" type="number" min="0" class="mt-1 block w-full rounded-lg border-slate-300">@error('sequence')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div></div>
        <div><label for="summary" class="block text-sm font-medium text-slate-700">Summary</label><textarea wire:model.blur="summary" id="summary" rows="2" class="mt-1 block w-full rounded-lg border-slate-300"></textarea>@error('summary')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
        <div><label for="objectives" class="block text-sm font-medium text-slate-700">Learning objectives <span class="text-slate-400">(one per line)</span></label><textarea wire:model.blur="objectives" id="objectives" rows="3" class="mt-1 block w-full rounded-lg border-slate-300"></textarea>@error('objectives')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
        <div><label for="content" class="block text-sm font-medium text-slate-700">Lesson content</label><x-ui.rich-text-editor wire:model="content" id="content" class="mt-1" placeholder="Write the lesson content, examples, and activities…" />@error('content')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
        <div><label for="status" class="block text-sm font-medium text-slate-700">Status</label><select wire:model.blur="status" id="status" class="mt-1 block w-full rounded-lg border-slate-300"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select>@error('status')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
        <div class="flex justify-end gap-3"><x-button type="button" wire:click="closeModals" variant="secondary" icon="close" target="closeModals">Cancel</x-button><x-button type="submit" variant="primary" icon="save" target="save">Save lesson</x-button></div>
    </form></x-modal>
    <x-modal :show="$showDeleteModal" title="Archive lesson?" close-action="closeModals" max-width="md"><p class="text-sm text-slate-600">The lesson will be archived and hidden from normal lists. You can restore it from the database if necessary.</p><x-slot:footer><div class="flex justify-end gap-3"><x-button wire:click="closeModals" variant="secondary" icon="close" target="closeModals">Cancel</x-button><x-button wire:click="delete" variant="danger" icon="trash" target="delete">Archive lesson</x-button></div></x-slot:footer></x-modal>
</div>
