<?php
namespace App\Livewire\LMS\Attendance;
use App\Models\{AcademicYear,AttendanceRecord,School,SchoolClass,Term}; use Illuminate\Foundation\Auth\Access\AuthorizesRequests; use Illuminate\Support\Facades\DB; use Illuminate\Validation\{Rule,ValidationException}; use Jantinnerezo\LivewireAlert\Facades\LivewireAlert; use Livewire\Attributes\Layout; use Livewire\Component; use Throwable;
#[Layout('layouts.lms')]
class Index extends Component { use AuthorizesRequests; public string $academicYearId='',$termId='',$classId='',$attendanceDate=''; public array $statuses=[],$remarks=[]; public bool $registerLoaded=false;
public function mount():void{$this->authorize('viewAny',AttendanceRecord::class);$this->attendanceDate=now()->toDateString();} public function loadRegister():void{$this->authorize('create',AttendanceRecord::class);$data=$this->validate(['academicYearId'=>['required','integer',Rule::exists('academic_years','id')],'termId'=>['required','integer',Rule::exists('terms','id')],'classId'=>['required','integer',Rule::exists('school_classes','id')],'attendanceDate'=>['required','date']]);$class=SchoolClass::findOrFail($data['classId']);abort_unless($class->academic_year_id==(int)$data['academicYearId']&&Term::whereKey($data['termId'])->where('academic_year_id',$class->academic_year_id)->exists(),422,'Choose a class and term from the same academic year.');$this->assertClassAccess($class);$existing=AttendanceRecord::where('school_class_id',$class->id)->whereDate('attendance_date',$data['attendanceDate'])->get()->keyBy('student_id');$this->statuses=[];$this->remarks=[];foreach($class->enrollments()->with('student')->where('status','active')->get() as $enrollment){$this->statuses[$enrollment->student_id]=$existing[$enrollment->student_id]->status??'present';$this->remarks[$enrollment->student_id]=$existing[$enrollment->student_id]->remarks??'';}$this->registerLoaded=true;}
public function save():void{$this->authorize('create',AttendanceRecord::class);try{$this->validate(['academicYearId'=>['required','integer'],'termId'=>['required','integer'],'classId'=>['required','integer'],'attendanceDate'=>['required','date'],'statuses'=>['required','array'],'statuses.*'=>[Rule::in(['present','absent','late','excused'])],'remarks'=>['array'],'remarks.*'=>['nullable','string','max:1000']]);$class=SchoolClass::findOrFail($this->classId);$this->assertClassAccess($class);DB::transaction(function(){$class=SchoolClass::findOrFail($this->classId);foreach($this->statuses as $studentId=>$status)AttendanceRecord::updateOrCreate(['student_id'=>$studentId,'school_class_id'=>$class->id,'attendance_date'=>$this->attendanceDate],['academic_year_id'=>$this->academicYearId,'term_id'=>$this->termId,'status'=>$status,'remarks'=>$this->remarks[$studentId]??null,'marked_by'=>auth()->id()]);});LivewireAlert::title('Attendance saved')->success()->asToast()->position('top-end')->show();}catch(ValidationException $e){LivewireAlert::title('Check the register')->error()->asToast()->position('top-end')->show();throw $e;}catch(Throwable $e){report($e);LivewireAlert::title('Unable to save attendance')->error()->asToast()->position('top-end')->show();}}
private function assertClassAccess(SchoolClass $class):void{if(auth()->user()->hasRole('teacher'))abort_unless($class->classSubjects()->where('teacher_id',auth()->user()->teacher?->id)->exists(),403);}
public function render(){$schoolId=School::query()->value('id');$teacherId=auth()->user()->hasRole('teacher')?auth()->user()->teacher?->id:null;$years=AcademicYear::where('school_id',$schoolId)->orderByDesc('starts_at')->get();return view('livewire.lms.attendance.index',['years'=>$years,'terms'=>Term::whereIn('academic_year_id',$years->pluck('id'))->orderBy('sequence')->get(),'classes'=>SchoolClass::whereIn('academic_year_id',$years->pluck('id'))->when($teacherId,fn($q)=>$q->whereHas('classSubjects',fn($subjects)=>$subjects->where('teacher_id',$teacherId)))->orderBy('name')->get(),'students'=>$this->registerLoaded?SchoolClass::find($this->classId)?->enrollments()->with('student')->where('status','active')->get()??collect():collect()]);}}
